name: spacex_demo
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  crew_member_repository:
    path: packages/crew_member_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  rocket_repository:
    path: packages/rocket_repository
  spacex_api:
    path: packages/spacex_api  
  url_launcher: ^6.1.5

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/src/gen/
  line_length: 80
  
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false

  assets:
    enabled: true
    package_parameter_enabled: false
