name: spacex_api
description: My SpaceX Api Dart package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

dependencies: 
  equatable: ^2.0.3 
  http: ^0.13.4 
  json_annotation: ^4.6.0
